package com.project.epms;

import java.util.List;
import java.lang.System;

rule "epms-rule-1"
        ruleflow-group "epms-rule1-ruleflow-group"
        dialect "java"

when
    booking:com.project.epms.Booking()
    matchingEquipment : com.project.epms.Booking($matchingEquipment : matchingEquipments)
    equipment: com.project.epms.Booking($equipmentList : availableEquipments)
    $equip : List() from collect (Booking(booking.getEquipmentCategory() == equipmentCategory && booking.getAccessory() == accessory && booking.getAccessoryOwner() == accessoryOwner) from $equipmentList)
then
    booking.setMatchingEquipments($equip);
end